### ISSUE TITLE
Banner is been shown to all users

### ISSUE THREAD

**Issue by divedo** [nautobot/nautobot-plugin-welcome-wizard#51]
### Environment
* Python version:  3.9.11
* Nautobot version:  1.2.10
* nautobot-welcome-wizard version:  1.0.3

### Expected Behavior
Just users with permissions to access this plugin can see plugin top banner.

### Observed Behavior
Even a user without any permissions would see plugin banner.

### Steps to Reproduce
1. Create a user without permissions, just active.
2. Activate 'HIDE RESTRICTED UI' parameter
3. Login and you would see '[The Nautobot Welcome Wizard can help you get started with Nautobot!](https://nemo.central.inditex.grp/plugins/welcome_wizard/dashboard/)'

**Comment by smk4664** [comment]
Thanks for the report! The banner was added prior to Nautobot support for plugins to allow banners. I am investigating if we can move to the Nautobot provided banner functionality.

**Comment by smk4664** [comment]
I was able to reproduce and have started migrating to the Nautobot Banner functionality in 1.2.0.
