### ISSUE TITLE
[Nautobot 1.4] Possibly add LocationType and Location recommendations to the banners?

### ISSUE THREAD

**Issue by glennmatthews** [nautobot/nautobot-plugin-welcome-wizard#55]
### Environment
* Nautobot version:  1.4.0a2
* nautobot-welcome-wizard version:  

### Proposed Functionality

- When creating a Location, warn the user if LocationTypes are not yet defined (this may be automatically supported with existing code?)
- When creating Location-aware models (such as Device, Prefix, etc.), even though Location is currently an *optional* field (not required), perhaps the plugin should add a banner to *suggest* that the user configure Locations if none are yet defined?

### Use Case

Ongoing support for new data models.

**Comment by joewesch** [comment]
> When creating a Location, warn the user if LocationTypes are not yet defined (this may be automatically supported with existing code?)

Confirmed this already works with existing code.
