### ISSUE TITLE
Missing views for action(s) add, import

### ISSUE THREAD

**Issue by daniejstriata** [nautobot/nautobot-plugin-welcome-wizard#58]
### Environment
* Python version:  Python 3.7.10
* Nautobot version:  1.4.1
* nautobot-welcome-wizard version:  1.1.0

I did a new install of nautobot with the welcome wizard for the first time. When I browse to the Welcome Wizard plugin page I see an error on the top of the page in red:
Missing views for action(s) add, import

![image](https://user-images.githubusercontent.com/13314239/186915184-d4f1cff0-0606-4438-8c4e-fc0fcc0de128.png)
I'm unsure if the error is because of a step missing from the installation of the wizard or if something else is broken/missing from Nautobot.

**Comment by smk4664** [comment]
This occurred when Nautobot added validation of action buttons. This issue was resolved in https://github.com/nautobot/nautobot-plugin-welcome-wizard/issues/56 and we will be creating a new release when we resolve  https://github.com/nautobot/nautobot-plugin-welcome-wizard/issues/55
