### ISSUE TITLE
Add Nautobot Documentation Support

### ISSUE THREAD

**Issue by smk4664** [nautobot/nautobot-plugin-welcome-wizard#61]
### Proposed Functionality
Make Welcome Wizard match other Nautobot Documentation.

### Use Case

Consistent Documentation style across all repositories.

**Comment by smk4664** [comment]
https://github.com/nautobot/nautobot-plugin-golden-config is a great example.

**Comment by chadell** [comment]
@cmsirbu will create a base PR with the proposal, so would be up to us to extend it

**Comment by smk4664** [comment]
I don't mind doing the work, I was opening up an issue to track. @itdependsnetworks I did the same with nautobot-plugin-chatops.
