### ISSUE TITLE
With Welcome Wizard installed cannot Add Devices to Virtualization / Cluster

### ISSUE THREAD

**Issue by JimmyKip** [nautobot/nautobot-plugin-welcome-wizard#62]
### Environment
* Python version: 3.9.14
* Nautobot version:  1.4.5
* nautobot-welcome-wizard version:  1.1.1

On clicking 'Add Devices' under a Cluster, be displayed the page form with details to add a device.

### Observed Behavior

Receive server error:

 Server Error

There was a problem with your request. Please contact an administrator.

The complete exception is provided below:

<class 'AttributeError'>

'NoneType' object has no attribute 'base_fields'

Python version: 3.9.14
Nautobot version: 1.4.5

### Steps to Reproduce
1. install Welcome Wizard plugin
2. Under Virtualisation - Cluster, click Add Devices

**Comment by smk4664** [comment]
Thanks for the report @JimmyKip I can reproduce this issue. I will be investigating this.

**Comment by smk4664** [comment]
I have a fix that I am testing and will try go get in today.
