### ISSUE TITLE
Filering on the device type / manufacturer import view buggy on Nautobot 1.5.2

### ISSUE THREAD

**Issue by joaopsys** [nautobot/nautobot-plugin-welcome-wizard#67]
### Environment
* Python version:  3.8.12
* Nautobot version:  1.5.2
* nautobot-welcome-wizard version:  1.1.2

### Expected Behavior

When importing device types or manufacturer, there used to be a filtering field allowing free-text search on both manufacturers and device types. That field is now gone, perhaps due to all the filtering updates that happened on Nautobot 1.5.x

### Observed Behavior

![image](https://user-images.githubusercontent.com/1836514/204587298-5d4c9129-1bd4-4ae8-a139-b94b2366362a.png)
![image](https://user-images.githubusercontent.com/1836514/204587345-8aeffd8c-da6a-459f-a3d1-8ea6e5c5d644.png)

### Steps to Reproduce
1. Open the device type or manufacturer import view
2. Verify that the filtering is either buggy or non-existent (in the case of manufacturer import)

**Comment by bryanculver** [comment]
_Should_ be as simple as changing this:
https://github.com/nautobot/nautobot-plugin-welcome-wizard/blob/5541effc49a989b3fa80df4a3d4586056f5ce1c3/welcome_wizard/templates/welcome_wizard/manufacturer.html#L1

to `{% extends 'generic/object_list.html' %} and removing the excess load tags.

This should keep compatibility to older releases as well.
